export type ScheduledPost = {
  scheduleId: string;
  planId?: string | null;
  scheduledAt: string;
  scheduledAtJst: string;
  scheduledDate: string;
  status: string;
  mainText: string;
  comment1: string;
  comment2: string;
  comment3: string;
  comment4: string;
  comment5: string;
  comment6: string;
  comment7: string;
  comment8: string;
  createdAt: string;
  updatedAt: string;
  templateId?: string | null;
  theme?: string | null;
  planStatus?: string | null;
};
