steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest'
      - '-f'
      - deploy/youtube-sync/Dockerfile
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - autostudio-youtube-sync
      - '--image'
      - gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest
      - '--region'
      - 'asia-northeast1'
      - '--service-account'
      - 'autostudio@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - YOUTUBE_BQ_DATASET_ID=autostudio_media
      - '--set-secrets'
      - GOOGLE_SERVICE_ACCOUNT_JSON=GOOGLE_SERVICE_ACCOUNT_JSON:latest,YOUTUBE_API_KEY=YOUTUBE_API_KEY:latest,YOUTUBE_CHANNEL_ID=YOUTUBE_CHANNEL_ID:latest,YOUTUBE_COMPETITOR_IDS=YOUTUBE_COMPETITOR_IDS:latest,YOUTUBE_OAUTH_CLIENT_ID=YOUTUBE_OAUTH_CLIENT_ID:latest,YOUTUBE_OAUTH_CLIENT_SECRET=YOUTUBE_OAUTH_CLIENT_SECRET:latest,YOUTUBE_OAUTH_REFRESH_TOKEN=YOUTUBE_OAUTH_REFRESH_TOKEN:latest
      - '--max-retries'
      - '3'
      - '--task-timeout'
      - '600s'
images:
  - gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest
