steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest'
      - '-f'
      - deploy/youtube-sync/Dockerfile
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - autostudio-youtube-sync
      - '--image'
      - gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - managed
      - '--no-allow-unauthenticated'
      - '--update-env-vars'
      - GOOGLE_SERVICE_ACCOUNT_JSON=$$GOOGLE_SERVICE_ACCOUNT_JSON,YOUTUBE_API_KEY=$$YOUTUBE_API_KEY,YOUTUBE_CHANNEL_ID=$$YOUTUBE_CHANNEL_ID,YOUTUBE_COMPETITOR_IDS=$$YOUTUBE_COMPETITOR_IDS,YOUTUBE_BQ_DATASET_ID=$$YOUTUBE_BQ_DATASET_ID,YOUTUBE_OAUTH_CLIENT_ID=$$YOUTUBE_OAUTH_CLIENT_ID,YOUTUBE_OAUTH_CLIENT_SECRET=$$YOUTUBE_OAUTH_CLIENT_SECRET,YOUTUBE_OAUTH_REFRESH_TOKEN=$$YOUTUBE_OAUTH_REFRESH_TOKEN
    secretEnv:
      - GOOGLE_SERVICE_ACCOUNT_JSON
      - YOUTUBE_API_KEY
      - YOUTUBE_CHANNEL_ID
      - YOUTUBE_COMPETITOR_IDS
      - YOUTUBE_BQ_DATASET_ID
      - YOUTUBE_OAUTH_CLIENT_ID
      - YOUTUBE_OAUTH_CLIENT_SECRET
      - YOUTUBE_OAUTH_REFRESH_TOKEN
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_SERVICE_ACCOUNT_JSON/versions/latest
      env: GOOGLE_SERVICE_ACCOUNT_JSON
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_API_KEY/versions/latest
      env: YOUTUBE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_CHANNEL_ID/versions/latest
      env: YOUTUBE_CHANNEL_ID
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_COMPETITOR_IDS/versions/latest
      env: YOUTUBE_COMPETITOR_IDS
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_BQ_DATASET_ID/versions/latest
      env: YOUTUBE_BQ_DATASET_ID
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_OAUTH_CLIENT_ID/versions/latest
      env: YOUTUBE_OAUTH_CLIENT_ID
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_OAUTH_CLIENT_SECRET/versions/latest
      env: YOUTUBE_OAUTH_CLIENT_SECRET
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_OAUTH_REFRESH_TOKEN/versions/latest
      env: YOUTUBE_OAUTH_REFRESH_TOKEN
images:
  - gcr.io/$PROJECT_ID/autostudio-youtube-sync:latest
