steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/autostudio-threads-sync:latest'
      - '-f'
      - deploy/threads-sync/Dockerfile
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/autostudio-threads-sync:latest'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - create
      - autostudio-threads-sync
      - '--image'
      - gcr.io/$PROJECT_ID/autostudio-threads-sync:latest
      - '--region'
      - 'asia-northeast1'
      - '--service-account'
      - 'autostudio@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - GOOGLE_SERVICE_ACCOUNT_JSON=$$GOOGLE_SERVICE_ACCOUNT_JSON,THREADS_TOKEN=$$THREADS_TOKEN,THREADS_BUSINESS_ID=$$THREADS_BUSINESS_ID,BQ_PROJECT_ID=$$BQ_PROJECT_ID
      - '--max-retries'
      - '3'
      - '--task-timeout'
      - '600s'
    secretEnv:
      - GOOGLE_SERVICE_ACCOUNT_JSON
      - THREADS_TOKEN
      - THREADS_BUSINESS_ID
      - BQ_PROJECT_ID
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_SERVICE_ACCOUNT_JSON/versions/latest
      env: GOOGLE_SERVICE_ACCOUNT_JSON
    - versionName: projects/$PROJECT_ID/secrets/THREADS_TOKEN/versions/latest
      env: THREADS_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/THREADS_BUSINESS_ID/versions/latest
      env: THREADS_BUSINESS_ID
    - versionName: projects/$PROJECT_ID/secrets/BQ_PROJECT_ID/versions/latest
      env: BQ_PROJECT_ID
images:
  - gcr.io/$PROJECT_ID/autostudio-threads-sync:latest