schedule: '0 7 * * *'
timeZone: 'Asia/Tokyo'
httpTarget:
  uri: https://REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/PROJECT_ID/services/autostudio-threads-sync:run
  httpMethod: POST
  headers:
    Content-Type: application/json
  oauthToken:
    serviceAccountEmail: scheduler-invoker@PROJECT_ID.iam.gserviceaccount.com